// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/reviewsys/test/pkg/pb/service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/reviewsys/test/pkg/pb/service.proto

It has these top-level messages:
	VersionResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Test service

type TestClient interface {
	GetVersion(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) GetVersion(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/service.Test/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Test service

type TestServer interface {
	GetVersion(context.Context, *google_protobuf.Empty) (*VersionResponse, error)
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Test/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).GetVersion(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _Test_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/reviewsys/test/pkg/pb/service.proto",
}

func init() { proto.RegisterFile("github.com/reviewsys/test/pkg/pb/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x50, 0x3d, 0x4b, 0x03, 0x41,
	0x10, 0x35, 0x20, 0x06, 0xb7, 0x11, 0xae, 0x90, 0xe3, 0xb4, 0x90, 0x88, 0x20, 0x68, 0x76, 0x40,
	0xcb, 0x34, 0x22, 0x88, 0xd6, 0x41, 0x2c, 0xec, 0x76, 0xcf, 0xc9, 0xba, 0x78, 0xd9, 0x59, 0x76,
	0x26, 0x17, 0xee, 0xdf, 0x8b, 0x77, 0x7b, 0x10, 0x4c, 0x91, 0x6e, 0x3e, 0xde, 0x07, 0xef, 0x29,
	0xed, 0xbc, 0x7c, 0x6f, 0xac, 0xae, 0x69, 0x0d, 0x09, 0x5b, 0x8f, 0x5b, 0xee, 0x18, 0x04, 0x59,
	0x20, 0xfe, 0x38, 0x88, 0x16, 0x18, 0x53, 0xeb, 0x6b, 0xd4, 0x31, 0x91, 0x50, 0x31, 0xcd, 0x6b,
	0x75, 0xe1, 0x88, 0x5c, 0x83, 0xd0, 0x9f, 0xed, 0x66, 0x05, 0xb8, 0x8e, 0xd2, 0x0d, 0xa8, 0xea,
	0x32, 0x3f, 0x4d, 0xf4, 0x60, 0x42, 0x20, 0x31, 0xe2, 0x29, 0x70, 0xfe, 0x2e, 0x76, 0x3c, 0x9b,
	0x6e, 0x25, 0x83, 0x46, 0x3d, 0x77, 0x18, 0xe6, 0xad, 0x69, 0xfc, 0x97, 0x11, 0x84, 0xbd, 0x21,
	0x93, 0xef, 0x77, 0xc0, 0xbc, 0x35, 0xce, 0x61, 0x02, 0x8a, 0xbd, 0xfc, 0xbe, 0xd5, 0xec, 0x4e,
	0x9d, 0x7d, 0x60, 0x62, 0x4f, 0x61, 0x89, 0x1c, 0x29, 0x30, 0x16, 0xa5, 0x9a, 0xb6, 0xc3, 0xa9,
	0x9c, 0x5c, 0x4d, 0x6e, 0x4f, 0x97, 0xe3, 0xfa, 0xf0, 0xa6, 0x8e, 0xdf, 0x91, 0xa5, 0x78, 0x52,
	0xea, 0x15, 0x25, 0xf3, 0x8a, 0x73, 0x3d, 0x84, 0xd1, 0x63, 0x52, 0xfd, 0xf2, 0x97, 0xb4, 0x2a,
	0xf5, 0xd8, 0xcc, 0x3f, 0x87, 0xd9, 0xd1, 0xf3, 0xcd, 0xe7, 0xf5, 0xa1, 0x5e, 0x17, 0xd1, 0xda,
	0x93, 0x5e, 0xf2, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff, 0x24, 0xdf, 0x8f, 0x58, 0x85, 0x01, 0x00,
	0x00,
}
